### ISSUE TITLE
小优化跟踪

### ISSUE THREAD

**Issue by uicestone** [uicestone/PTER#1]
- [x] banner 副标题放大
- [x] service list
- [x] logo to homepage
- [x] 使用指南 Free Trial 立即订阅
- [x] 首页显示联系我们和二维码
- [x] 菜单字体放大
- [x] tip列表页不显示详情
- [x] 服务项目显示在免费技巧下
- [x] rand after timer
- [x] audio pause replay
- [x] 副标题颜色

**Comment by brendajx** [comment]
首页三个按钮改成：“Free trial，使用指南，获取优惠码”，“使用指南”和“获取优惠码”都是一篇文章
