### ISSUE TITLE
模考体验优化和错误修复

### ISSUE THREAD

**Issue by uicestone** [uicestone/PTER#54]
- [ ] Read Aloud	3秒未说话未停止录音	3秒未说话，应停止录音	暂不支持
- [x] Answer Short Question	录音无法播放	录音可以播放
    Uice: 我这边现在可以播放
- [ ] Repeat Sentence	有复述倒数计时	无倒数计时，口语应该都是3秒未说话，停止计时	
- [ ] Summarize Written Text	每题目前是单独10分钟计时，但如果提前完成，总体计时并未扣除10分钟，只是扣除了之前消耗的时间
- [ ] SWT 3题，每题单独10分钟，10分钟到，不可再作答
- [ ] Write Essay，单独及时20分钟	
- [ ] Write Essay	总体倒计时目前存在超过20分钟可能	进入本题型，计时变成20分钟	
## Reading			
- [x] Fill in the Blanks	发现提交本题后，仍然可以做答和修改答案	所有题型，提交本题后，不可再修改当前题型, 当前页面应该只能点击下一题	
- [ ] FIB 有个4分钟倒计时	模考无倒计时（平时练习可以保留不受影响）	
## Listening			
- [ ] 题型目前可跳过录音，直接提交	所有题型必须在录音播放完成后，才可进行提交本题，跳至下一题。	这个功能最后调整，不然我无法一直按下一题。
- [x] 参考答案	没有存储考生考试的录音	可以显示考生考试的录音做答。	
- [x] 没有存储写作的文字输入	可以存储考生考试的文字输入。
    确保写作的题目题型为Write Essay，即可存储	
- [x] 核对按钮貌似没有用处	可否换成上一题按钮	
- [ ] 考生在考完退出后，是否在个人中心有地方可以浏览试卷	个人中心- 可浏览做答的考卷

**Comment by xuebinpuma** [comment]
参考答案- 语言存储，目前只有Answer short Question 成功存储了，其他口语题型, 如 Retell Lecture, Read Aloud, Describe Image 都没有存储成功。

**Comment by xuebinpuma** [comment]
2. 网站选题BUG - 目前网站原本右上侧下拉选题，目前选了没有反应。
3. Paypal 付款逻辑 - 有报告说有BUG无法付款，能否测一下

**Comment by xuebinpuma** [comment]
LISTENING  23 Feb

1. multiple choice-multiple answers 音频播放前，增加一个准备时间倒计时现实，时间为 “7秒”，倒计时结束开始播放音频
2. Summarise Spoken Text 音频播放前，增加一个准备时间倒计时，时间为 ‘12秒’ 【此功能仅用在模考】
3. Fill-in-the-blanks, 音频播放前，准备倒计时 【7秒】
4. Highlight incorrect summary, 音频播放前，准备倒计时 【10秒】
5. Multiple choice - singe answer, 音频播放前，准备倒计时 【5秒】
6. Selecting missing words, 音频播放前，准备倒计时 【7秒】
7. Highlight incorrect words,  音频播放前，准备倒计时 【10秒】
8. Write from dictation, 音频播放前，准备时间【7秒】 仅限于模考
- over-

**Comment by xuebinpuma** [comment]
24 Feb Bug 
1. Paypal 通道是否已经确认？
2. Repeat Sentence， 录音时间目前是10秒，应该要有15秒 ==> 【整为15秒】
3. Repeat Sentence - Review Answer 界面， "Only questions 2,3, 10, 11 能看到自己的答案,  Questions 1,4,5,6,7,8,9- 自己的答案看不到，而是要录音"，【修复 语音存储功能】
4. Read Aloud - Review answers 时无法检查答案而是要录音，【检查答案界面，都去掉可以再录音的功能】
5. Speaking- Retell Lecture, 计时器不限时具体倒数秒数 【IT 去除具体的数字显示】
6. 同昨天的Answer Short Question - 检查答案界面 - "几乎所有题目能看到模范答案（文字）但听不到自己的录音/答案； Item 5-听到自己的答案； Item 10- 听到自己的答案 【修复语言存储】

**Comment by uicestone** [comment]
你每个问题，至少每一类问题要开新的Issue，不然没办法跟踪。你可以先吧之前随便开的那个Issue编辑一下重开。 @xuebinpuma

**Comment by xuebinpuma** [comment]
关闭这里所有的修复
