### ISSUE TITLE
模考-Listening- 音频播放前倒数计时器

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#60]
**Listening**
- [ ] 1.	multiple choice-multiple answers 音频播放前，增加一个准备时间倒计时现实，时间为 “7秒”，倒计时结束开始播放音频

- [ ] 2.	Summarise Spoken Text 音频播放前，增加一个准备时间倒计时，时间为 ‘12秒’ 

- [ ] 3.	Fill-in-the-blanks, 音频播放前，准备倒计时 【7秒】

- [ ] 4.	Highlight incorrect summary, 音频播放前，准备倒计时 【10秒】

- [ ] 5.	Multiple choice - singe answer, 音频播放前，准备倒计时 【5秒】

- [ ] 6.	Selecting missing words, 音频播放前，准备倒计时 【7秒】

- [ ] 7.	Highlight incorrect words, 音频播放前，准备倒计时 【10秒】

- [ ] 8.	Write from dictation, 音频播放前，准备时间【7秒】

口语 

- [ ] 	Repeat Sentence， 录音时间目前是10秒，==> 【调整为15秒】

**Comment by uicestone** [comment]
后台已经可以配置：

- 在后台题型一栏找到“题型分类”
- 搜索想要考试延时的题型
- 点击编辑
- 在考试准备时间输入秒数
