### ISSUE TITLE
模拟写作计时（PTE）

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#66]
模考写作

- [x] Item 37(summarise Written text) 单独计时10分钟，10分钟到，文字框不可再输入内容
 Item 38 (summarise written text), 单独计时10分钟， 10分钟到，文字框不可再输入内容
Item 39(summarise written text) 单独计时10分钟，10分钟到，文字框不可再输入内容
Item 40 (Write essay) 单独计时20分钟，10分钟到，文字框不可再输入内容

- [x] 将目前写作总计时30分钟（1800秒）总计时，修正为40分钟（2400秒）总计时

- [x] BUG, Write Essay 时间到了后，又开始重新计时了。

https://www.bingotraining.com/exam/%E6%A8%A1%E6%8B%9F%E9%A2%981/?paper_id=9448&section=writing&exercise_index=3

**Comment by uicestone** [comment]
ea9ca127e72e9d9abb7638c945fa6748a4bc88c2 和 09e2b7bd87b85cf368ff807f1b7ecde8d3028241
