### ISSUE TITLE
模拟题听力计时（PTE）

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#68]
听力，前两个题目Summarize Spoken Text 是单独10分钟计时，如果做的快，后面的总计时也应该是扣除20分钟。 如果这两题10分钟到了，应该无法再继续输入文字。

具体链接
https://www.bingotraining.com/exercise/summarize-spoken-text-1-2/  
https://www.bingotraining.com/exercise/%E6%A8%A1%E6%8B%9F%E9%A2%98-summarize-spoken-text-2/

**Comment by uicestone** [comment]
@xuebinpuma 听力的2400秒已经包含了这个2个600秒？

**Comment by xuebinpuma** [comment]
对的，已经包含。
如果300秒，300秒，没有全部用完就进入下一题，总时间应该都当作扣除300秒，300秒计算
如果300秒，300秒走完，还迟迟未按下一题，总时间应该继续走
当然，300秒题型时间到应该不可再做答

**Comment by uicestone** [comment]
已经在 ea9ca127e72e9d9abb7638c945fa6748a4bc88c2 中完成

**Comment by xuebinpuma** [comment]
提交时未扣减300秒，重开此问题
