### ISSUE TITLE
免费练习（网站正常使用报错）

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#71]
未注册用户，在免费体验-练习中，按个几下”下一题“，便跳转到了注册页面，原本是按”下一题“ 都可以做一遍免费体验的题目。

https://www.bingotraining.com/exercise/repeat-sentence-%E7%BB%83%E4%B9%A01/?tag=free-trial

**Comment by uicestone** [comment]
这个原因在Free Trial标签题目不能打上其他标签，如限时免费。
