### ISSUE TITLE
价格表修改(PTE)

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#74]
一二三月价格套餐- 字样、顺序、与价格调整 （见图示）

![img-4425](https://user-images.githubusercontent.com/33593946/37704676-962199e0-2d4d-11e8-8169-740fdb75d498.JPG)

 (***注意，这个2次只是让学生以为2次，其实不是2次，这样以后就不用调整NAATI的逻辑了，因为NAATI也是走考试逻辑，但其实是可以无限练的）

**Comment by uicestone** [comment]
后台价格，价格表页面和首页价格表截图都已经更新
