### ISSUE TITLE
CCL翻译

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#76]
- [x] 创建新价格表单 【见附件】
[CCL.docx](https://github.com/uicestone/PTER/files/1934180/CCL.docx)

- [ ] 首页增添CCL独立按钮，首页头条四个都有独立按钮，且允许我自行操作修改文字
       首页独立CCL按钮的图片，可以临时用这个
https://www.bingotraining.com/wp-content/uploads/2017/07/iStock-528500713.jpg

首页服务位置图片
![default](https://user-images.githubusercontent.com/33593946/39080909-05afb16c-457b-11e8-8102-7e84ebd0d358.PNG) 

- [x] 建立专项付款通道(Paypal & Royalpal)
       **Paypal** Email address: wechat@bingotraining.com; 
             Business information: BINGO TRAINING NAATI PTY LTD
- [x] 建立CCL 考试列表页面，页面展示可选考试.

- [x] 建立CCL 考试字段（**优先**，涉及题目上传与考题预览）. 并将目前练习-NAATI-对话的功能改为，播放音频+录音| **计时调整为40秒，目前是1分钟**

***此处显示的是40秒，走的时候是走的1分钟，走的时间应该也是40秒

**Comment by uicestone** [comment]
考试列表页面：
https://www.bingotraining.com/exam/?type=ccl，带翻页，样式比较简单

考试详情页也已经可以考试和对答案，但暂时保留了一个3000秒的总计时。

**Comment by xuebinpuma** [comment]
考试页面进入后，未成功加载题目。即进入考试，看不到字段处添加的题目。

**Comment by xuebinpuma** [comment]
![capture3](https://user-images.githubusercontent.com/33593946/39079120-cd1836e4-4557-11e8-8203-b3aa70cdbb1b.PNG)
如图，测试该套题目时，出现过一次音频放完未出现录音的BUG，在此情况下，按下一题也一直没有用。
请一并检测一下这个与昨天测试发现的语音错位问题，确保用户练习时候语音录音没有问题，谢谢。

**Comment by xuebinpuma** [comment]
试着用你的测试号进入考试列表页面，然后选择其中一个考试，目前跳出的付费界面仍是PTE的付费界面

**Comment by uicestone** [comment]
首页按钮现在支持自定义了：

- 添加或编辑一篇文章，并设置为头条*分类*（注意不是标签了）
- 文章下会出现“按钮文字”和“按钮链接”，编辑保存
