### ISSUE TITLE
精听识别

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#83]
修改精听识别为
大小写不正确不算错误
标点符号不正确不算错误- 这样（一瞥s)是不是也不算错误了
https://www.bingotraining.com/exercise/%E7%B2%BE%E5%90%AC%E7%BB%83%E4%B9%A08/

**Comment by uicestone** [comment]
注意一下目前句末的点号“.”、所有的“'”、“?”、“!”、“-”、“<”、“>”是不参与比较的。

**Comment by uicestone** [comment]
大小写好了，看一下 @xuebinpuma
