### ISSUE TITLE
CCL免费试用题型-标签用哪个

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#84]
考试列表免费试用的题目，我该用什么标签，"free Trial"吗？
我在Speech therapist 试加了Free Trial，但仍然会需要登入。

https://www.bingotraining.com/register/?intend=/exam/naati_ccl%E8%80%83%E8%AF%95-%E6%95%99%E8%82%B2%E7%AF%87_speech-therapist/?paper_id=13048

**Comment by uicestone** [comment]
我这边测试是可以的。测试访客账号`uicestone1`密码`123`

**Comment by xuebinpuma** [comment]
目前测试下来情况如下
1. 先点击链接，然后登入的，是可以
2. 先登录，再点击该链接，仍然出现要求注册的界面

**Comment by uicestone** [comment]
@xuebinpuma 我先登录uicestone1，然后访问这个考试，也是可以的。但是注意你贴出的链接是错误的，正确的链接是
```
https://www.bingotraining.com/exam/naati_ccl%E8%80%83%E8%AF%95-%E6%95%99%E8%82%B2%E7%AF%87_speech-therapist/
```
你的链接已经是注册跳转链接了

**Comment by xuebinpuma** [comment]
登录可以，按点击考试后，直接跳转了付款界面

![capture6](https://user-images.githubusercontent.com/33593946/39080768-8fc0bf84-4578-11e8-8f2a-868786a4d701.PNG)
https://www.bingotraining.com/pricing-table/?intend=%2Fexam%2Fnaati_ccl%25e8%2580%2583%25e8%25af%2595-%25e6%2595%2599%25e8%2582%25b2%25e7%25af%2587_speech-therapist%2F%3Fpaper_id%3D13210

**Comment by uicestone** [comment]
哦我知道了，那是因为跳转到了练习页面，练习没有标记Free Trial。我可以修改一下逻辑。
