### ISSUE TITLE
精听准确度

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#85]
https://www.bingotraining.com/exercise/%E6%A8%A1%E6%8B%9F%E5%89%8D%E7%BB%83%E4%B9%A0%E7%B2%BE%E5%90%AC%EF%BC%89-nasa/

复制了一摸一样的答案，但准确度为何还是98%，而且检查也没有显示错误。
文本如下

In this lecture, we will be talking about NASA, what it stands for and some of its major responsibilities.

NASA is a United States government agency which stands for National Aeronautics and Space Administration which was formed in 1958 and responsible for science and technology related to air and space. NASA is currently engaged in many activities. For instance, astronauts in orbit conduct scientific research. Satellites help scientists learn more about Earth. Space probes study the solar system, and beyond. New developments improve air travel and other aspects of flight. NASA is also beginning a new program to send humans to explore beyond the moon to Mars.

In addition to those major missions, NASA also shares what it learns, so that its information can make life better for people all over the world. For example, companies can use NASA discoveries to create new products. NASA’s Education Office helps teachers to prepare the students who will be the engineers, scientists, astronauts and other potential NASA workers.  NASA has a tradition of investing in programs and activities that inspire and engage students, educators, families and communities in the excitement and discovery of exploration. NASA offers training to help teachers learn new ways to teach science, technology, engineering and mathematics. The agency also involves students in NASA missions to help them get excited about learning.

**Comment by uicestone** [comment]
好了，换行问题。
