### ISSUE TITLE
CCL词汇题型=Repeat Sentence功能

### ISSUE THREAD

**Issue by xuebinpuma** [uicestone/PTER#86]
- [ ] NAATI父级菜单下增加了题型

- CCl初阶词汇
- CCL中阶词汇
- CCL高阶词汇
功能= Repeat Sentence的功能
“复述”时间 改为 “翻译” = 3秒
不影响PTE

- [ ] NAATI父级菜单下增加了题型
-CCL精听练习
功能=PTE精听练习的功能
不影响PTE

抱歉之前没完全考虑周全，帮我加一下谢谢！

**Comment by uicestone** [comment]
你这是CCL里的Repeat Sentence？不影响PTE？

**Comment by xuebinpuma** [comment]
对，只是CCL的
其实是CCL的词汇背诵
只是功能和Repeat Sentence 类似
把复述时间改为，“翻译=3秒”
